# Generated by Django 3.2.16 on 2025-05-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_updated_at'),
    ]

    operations = [
    ]

migrations.RemoveField(
    model_name='comment',
    name='updated_at',
),